# Generated by Django 3.0.7 on 2026-04-10 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0022_auto_20260410_1614'),
        ('sponsor', '0005_auto_20171109_1519'),
    ]

    operations = [
    ]
