# Generated by Django 3.0.7 on 2026-04-10 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0023_auto_20260410_1627'),
        ('sponsor', '0006_auto_20260410_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocuments',
            name='document',
            field=models.FileField(upload_to=sponsor.models.project_image_path),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to=sponsor.models.project_image_path),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=sponsor.models.sponsor_logo_path),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'sponsor'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorcontact',
            name='status',
            field=models.CharField(choices=[('0', 'InActive'), ('1', 'Active')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsorproject',
            name='project_type',
            field=models.CharField(choices=[('1', 'Intervention'), ('2', 'Collection')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsorproject',
            name='status',
            field=models.CharField(choices=[('1', 'Planned'), ('2', 'Activated'), ('3', 'Closed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsorprojectdetailssubfields',
            name='quarter',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsorprojectdetailssubfields',
            name='status',
            field=models.CharField(choices=[('1', 'Initiated'), ('2', 'In-progress'), ('3', 'Completed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsorprojectmou',
            name='quarter',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectdetails',
            unique_together={('sponsor_project', 'slum')},
        ),
    ]
