# Generated by Django 3.0.7 on 2020-12-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0022_auto_20181213_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='phase',
            field=models.CharField(blank=True, choices=[('1', 'Phase One'), ('2', 'Phase Two'), ('3', 'Phase Three')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='unit',
            field=models.CharField(blank=True, choices=[('1', 'Tempo/Piago'), ('2', 'Bags'), ('3', 'Nos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toiletconstruction',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Agreement done'), ('2', 'Agreement cancel'), ('3', 'Material not given'), ('4', 'Construction not started'), ('5', 'Under construction'), ('6', 'Completed'), ('7', 'Written-off')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CommunityMobilizationActivityAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_activity', models.DateTimeField()),
                ('household_number', models.CharField(max_length=10)),
                ('males_attended_activity', models.IntegerField()),
                ('females_attended_activity', models.IntegerField()),
                ('other_gender_attended_activity', models.IntegerField()),
                ('girls_attended_activity', models.IntegerField()),
                ('boys_attended_activity', models.IntegerField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastersheet.ActivityType')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.City')),
                ('slum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Slum')),
            ],
        ),
    ]
