# Generated by Django 3.0.7 on 2025-09-09 10:06

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20190927_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeward',
            name='background_color',
            field=colorfield.fields.ColorField(default='#BFFFD0', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='border_color',
            field=colorfield.fields.ColorField(default='#BFFFD0', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ward', to='master.City'),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='ward_no',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='city',
            name='background_color',
            field=colorfield.fields.ColorField(default='#94BBFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='border_color',
            field=colorfield.fields.ColorField(default='#94BBFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='drainage',
            name='drainage_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/FactsheetPhotos/'),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='administrative_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_ward', to='master.AdministrativeWard'),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFEFA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='border_color',
            field=colorfield.fields.ColorField(default='#FFEFA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='ward_code',
            field=models.TextField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='ward_no',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_report_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/FactsheetPhotos/'),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='general_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='general_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='general_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='gutter_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='gutter_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='gutter_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='road_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='roads_and_access_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='roads_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='toilet_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='toilet_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='toilet_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='waste_management_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='waste_management_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='waste_management_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='water_image_bottomdown1',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='water_image_bottomdown2',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='water_info_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/', verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='city',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'All'), ('2', 'Allow Selection')]),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='slum',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'All'), ('2', 'Allow Selection')]),
        ),
        migrations.AlterField(
            model_name='slum',
            name='electoral_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slum_name', to='master.ElectoralWard'),
        ),
        migrations.AlterField(
            model_name='slum',
            name='factsheet',
            field=models.FileField(blank=True, null=True, upload_to='factsheet/'),
        ),
        migrations.AlterField(
            model_name='slum',
            name='odf_status',
            field=models.CharField(choices=[('', ''), ('OD', 'OD'), ('ODF', 'ODF'), ('ODF+', 'ODF+'), ('ODF++', 'ODF++')], default=(('', ''), ('OD', 'OD'), ('ODF', 'ODF'), ('ODF+', 'ODF+'), ('ODF++', 'ODF++')), max_length=2048),
        ),
        migrations.AlterField(
            model_name='slum',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='factsheet/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('Slum Level', 'Slum Level'), ('Household Level', 'Household Level'), ('Household Member Level', 'Household Member Level'), ('Family Factsheet', 'Family Factsheet')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='wardofficecontact',
            name='address_info',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
