# Generated by Django 3.0.7 on 2025-10-09 06:35

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20250909_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='drainage_report_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='general_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='general_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='general_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='gutter_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='gutter_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='gutter_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='road_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='roads_and_access_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='roads_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='toilet_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='toilet_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='toilet_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='waste_management_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='waste_management_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='waste_management_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='water_image_bottomdown1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='water_image_bottomdown2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
        migrations.AlterField(
            model_name='rapid_slum_appraisal',
            name='water_info_left_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=master.models.rapid_slum_upload_path, verbose_name=master.models.Rapid_Slum_Appraisal.validate_image),
        ),
    ]
