# Generated by Django 3.2.25 on 2026-04-03 10:12

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_auto_20251009_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='slum',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('sra', 'Gone for SRA'), ('road_widening', 'Gone for Road Widening')], max_length=50, null=True),
        ),
    ]
