# Generated by Django 3.2.25 on 2026-04-06 11:25

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20260403_1542'),
    ]

    operations = [

        migrations.CreateModel(
            name='SlumTransformationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year photo was taken e.g. 2019')),
                ('photo', models.ImageField(upload_to='slum_transformation/%Y/')),
                ('description', models.TextField(blank=True)),
                ('coordinates', models.JSONField(help_text='{"top_left":[lat,lng],"top_right":[lat,lng],"bottom_right":[lat,lng],"bottom_left":[lat,lng]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slum', models.ForeignKey(limit_choices_to={'current_status': 'sra'}, on_delete=django.db.models.deletion.CASCADE, related_name='transformation_photos', to='master.slum')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
