# Generated by Django 3.2.25 on 2026-04-06 11:31

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20260406_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slumtransformationphoto',
            options={'ordering': ['month_year']},
        ),
        migrations.RemoveField(
            model_name='slumtransformationphoto',
            name='year',
        ),
        migrations.AddField(
            model_name='slumtransformationphoto',
            name='month_year',
            field=models.DateField(blank=True, help_text='Month and year of photo e.g. 2019-06-01 (day is ignored)', null=True),
        ),
 
    ]
