# Generated by Django 3.2.25 on 2026-04-06 11:42

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion

from jsonfield import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20260406_1701'),
    ]

    operations = [

        migrations.AlterField(
            model_name='slumtransformationphoto',
            name='coordinates',
            field=JSONField(help_text='{"north": 16.6851, "south": 16.6825, "east": 74.1927, "west": 74.1887}'),
        ),
    ]
