# Generated by Django 3.2.25 on 2026-04-06 11:48

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_auto_20260406_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('Slum Level', 'Slum Level'), ('Household Level', 'Household Level'), ('Household Member Level', 'Household Member Level'), ('Family Factsheet', 'Family Factsheet')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='wardofficecontact',
            name='address_info',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
