# Generated by Django 3.2.25 on 2026-04-06 12:04

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_auto_20260406_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slumtransformationphoto',
            name='photo',
            field=models.ImageField(upload_to=master.models.slum_photo_upload_path),
        ),
    ]
