# Generated by Django 3.2.25 on 2026-04-09 06:26

from django.db import migrations, models
import django.db.models.deletion
import master.models
from jsonfield import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_slumtransformationphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlumTransformationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=master.models.slum_photo_upload_path)),
                ('caption', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlumTransformationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(blank=True, help_text='Use first day of month (YYYY-MM-01)', null=True)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, upload_to=master.models.slum_photo_upload_path)),
                ('coordinates', JSONField(help_text='{"north": ..., "south": ..., "east": ..., "west": ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slum', models.ForeignKey(limit_choices_to={'current_status': 'sra'}, on_delete=django.db.models.deletion.CASCADE, related_name='transformation_phases', to='master.slum')),
            ],
            options={
                'ordering': ['month_year'],
            },
        ),
        migrations.DeleteModel(
            name='SlumTransformationPhoto',
        ),
        migrations.AddField(
            model_name='slumtransformationimage',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='master.slumtransformationphase'),
        ),
        migrations.AddConstraint(
            model_name='slumtransformationimage',
            constraint=models.UniqueConstraint(fields=('phase', 'priority'), name='unique_priority_per_phase'),
        ),
    ]
