# Generated by Django 3.0.7 on 2026-04-10 10:44

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_auto_20260409_1156'),
    ]

    operations = []
