# Generated by Django 3.0.7 on 2026-04-10 10:57

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20260410_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeward',
            name='background_color',
            field=colorfield.fields.ColorField(default='#BFFFD0', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='border_color',
            field=colorfield.fields.ColorField(default='#BFFFD0', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ward', to='master.City'),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326),
        ),
        migrations.AlterField(
            model_name='administrativeward',
            name='ward_no',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='city',
            name='background_color',
            field=colorfield.fields.ColorField(default='#94BBFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='border_color',
            field=colorfield.fields.ColorField(default='#94BBFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='drainage',
            name='drainage_image',
            field=models.ImageField(blank=True, null=True, upload_to='ShelterPhotos/FactsheetPhotos/'),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='administrative_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_ward', to='master.AdministrativeWard'),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFEFA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='border_color',
            field=colorfield.fields.ColorField(default='#FFEFA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='ward_code',
            field=models.TextField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='electoralward',
            name='ward_no',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='city',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'All'), ('2', 'Allow Selection')]),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='slum',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'All'), ('2', 'Allow Selection')]),
        ),
        migrations.AlterField(
            model_name='slum',
            name='electoral_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slum_name', to='master.ElectoralWard'),
        ),
        migrations.AlterField(
            model_name='slum',
            name='factsheet',
            field=models.FileField(blank=True, null=True, upload_to='factsheet/'),
        ),
        migrations.AlterField(
            model_name='slum',
            name='odf_status',
            field=models.CharField(choices=[('', ''), ('OD', 'OD'), ('ODF', 'ODF'), ('ODF+', 'ODF+'), ('ODF++', 'ODF++')], default=(('', ''), ('OD', 'OD'), ('ODF', 'ODF'), ('ODF+', 'ODF+'), ('ODF++', 'ODF++')), max_length=2048),
        ),
        migrations.AlterField(
            model_name='slum',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='factsheet/'),
        ),
    ]
