# Generated by Django 3.2.25 on 2026-03-24 07:13

import component.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('component', '0006_auto_20190625_1750'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='section',
            options={'permissions': [('can_refresh_section', 'Can refresh sections')], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
