# Generated by Django 3.0.7 on 2026-04-10 10:44

import component.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('component', '0007_auto_20260324_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AlterField(
            model_name='component',
            name='content_type',
            field=models.ForeignKey(default=component.models.get_default_slum_content_type, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='display_type',
            field=models.CharField(choices=[('M', 'Map'), ('T', 'Tabular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='componentIcons/'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='level',
            field=models.CharField(choices=[('C', 'City'), ('S', 'Slum'), ('H', 'Household')], max_length=1),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(choices=[('C', 'Component'), ('F', 'Filter'), ('S', 'Sponsor')], max_length=1),
        ),
    ]
