# Generated by Django 3.0.7 on 2026-04-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0008_auto_20260410_1614'),
    ]

    operations = [
    ]
