# Generated by Django 3.2.25 on 2026-02-19 07:27

from django.db import migrations, models
import django.db.models.deletion
from reports.models import sponsor_project_photo_upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.deliverable')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProjectMonthlyReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgressParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProjectReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliverables', models.ManyToManyField(related_name='project_reports', through='reports.SponsorProjectDeliverable', to='reports.Deliverable')),
                ('project_locations', models.ManyToManyField(related_name='sponsor_project_reports', to='master.Slum')),
                ('sponsor_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='sponsor.sponsorproject')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProjectMonthlyWorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_progress', to='reports.sponsorprojectmonthlyreportdetails')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.workprogressparameter')),
            ],
        ),
        migrations.AddField(
            model_name='sponsorprojectmonthlyreportdetails',
            name='project_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='reports.sponsorprojectreportdetails'),
        ),
        migrations.AddField(
            model_name='sponsorprojectmonthlyreportdetails',
            name='work_parameters',
            field=models.ManyToManyField(related_name='monthly_reports', through='reports.SponsorProjectMonthlyWorkProgress', to='reports.WorkProgressParameter'),
        ),
        migrations.CreateModel(
            name='SponsorProjectMonthlyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sponsor_project_photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.sponsorprojectmonthlyreportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProjectMonthlyDeliverableAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.deliverable')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_achievements', to='reports.sponsorprojectmonthlyreportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProjectMonthlyBeneficiaryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.beneficiaryindicator')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_values', to='reports.sponsorprojectmonthlyreportdetails')),
            ],
        ),
        migrations.AddField(
            model_name='sponsorprojectdeliverable',
            name='project_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_deliverables', to='reports.sponsorprojectreportdetails'),
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlyworkprogress',
            index=models.Index(fields=['monthly_report'], name='reports_spo_monthly_8ed8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlyworkprogress',
            index=models.Index(fields=['parameter'], name='reports_spo_paramet_4107e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectmonthlyworkprogress',
            unique_together={('monthly_report', 'parameter')},
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlyreportdetails',
            index=models.Index(fields=['project_report', 'month'], name='reports_spo_project_3ec599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectmonthlyreportdetails',
            unique_together={('project_report', 'month')},
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlydeliverableachievement',
            index=models.Index(fields=['monthly_report'], name='reports_spo_monthly_9c3881_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlydeliverableachievement',
            index=models.Index(fields=['deliverable'], name='reports_spo_deliver_94f348_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectmonthlydeliverableachievement',
            unique_together={('monthly_report', 'deliverable')},
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlybeneficiaryvalue',
            index=models.Index(fields=['monthly_report'], name='reports_spo_monthly_7ea3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlybeneficiaryvalue',
            index=models.Index(fields=['indicator'], name='reports_spo_indicat_212f01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectmonthlybeneficiaryvalue',
            unique_together={('monthly_report', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectdeliverable',
            unique_together={('project_report', 'deliverable')},
        ),
    ]
