# Generated by Django 3.2.25 on 2026-03-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiaryindicator',
            options={'verbose_name': 'Beneficiary indicator', 'verbose_name_plural': '10. Beneficiary indicators'},
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'verbose_name': 'Deliverable', 'verbose_name_plural': '08. Deliverables'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectdeliverable',
            options={'verbose_name': 'Project deliverable', 'verbose_name_plural': '02. Project deliverables'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlybeneficiaryvalue',
            options={'verbose_name': 'Monthly beneficiary value', 'verbose_name_plural': '05. Monthly beneficiary values'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlydeliverableachievement',
            options={'verbose_name': 'Monthly deliverable achievement', 'verbose_name_plural': '06. Monthly deliverable achievements'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlyphoto',
            options={'verbose_name': 'Monthly photo', 'verbose_name_plural': '07. Monthly photos'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlyreportdetails',
            options={'verbose_name': 'Monthly report', 'verbose_name_plural': '03. Monthly reports'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlyworkprogress',
            options={'verbose_name': 'Monthly work progress', 'verbose_name_plural': '04. Monthly work progress'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectreportdetails',
            options={'verbose_name': 'Sponsor project report', 'verbose_name_plural': '01. Sponsor project reports'},
        ),
        migrations.AlterModelOptions(
            name='workprogressparameter',
            options={'verbose_name': 'Work progress parameter', 'verbose_name_plural': '09. Work progress parameters'},
        ),
        migrations.RemoveIndex(
            model_name='sponsorprojectmonthlyworkprogress',
            name='reports_spo_monthly_8ed8ef_idx',
        ),
        migrations.AddField(
            model_name='sponsorprojectmonthlyworkprogress',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_work_progress', to='master.slum'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectmonthlyworkprogress',
            unique_together={('monthly_report', 'location', 'parameter')},
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlyworkprogress',
            index=models.Index(fields=['monthly_report', 'location'], name='reports_spo_monthly_477bd3_idx'),
        ),
    ]
