# Generated by Django 3.2.25 on 2026-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20260310_1207'),
    ]

    operations = []
