# Generated by Django 3.2.25 on 2026-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20260310_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='deliverable_icons/'),
        ),
    ]
