# Generated by Django 3.2.25 on 2026-03-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_deliverable_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='abbrevation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
