# Generated by Django 3.2.25 on 2026-03-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_deliverable_abbrevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary_indicator_icons/'),
        ),
    ]
