# Generated by Django 3.2.25 on 2026-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_beneficiaryindicator_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('task', models.CharField(max_length=50)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('task', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expiry_time', models.DateTimeField()),
            ],
            options={
                'unique_together': {('email', 'task')},
            },
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['email', 'task'], name='reports_for_email_e7080a_idx'),
        ),
    ]
