# Generated by Django 3.2.25 on 2026-03-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20260316_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSubmission',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
