# Generated by Django 3.0.7 on 2026-04-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_auto_20260410_1627'),
        ('reports', '0008_auto_20260316_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiaryindicator',
            options={'verbose_name': 'Beneficiary indicator', 'verbose_name_plural': '10. Beneficiary indicators'},
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'verbose_name': 'Deliverable', 'verbose_name_plural': '08. Deliverables'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectdeliverable',
            options={'verbose_name': 'Project deliverable', 'verbose_name_plural': '02. Project deliverables'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlybeneficiaryvalue',
            options={'verbose_name': 'Monthly beneficiary value', 'verbose_name_plural': '05. Monthly beneficiary values'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlydeliverableachievement',
            options={'verbose_name': 'Monthly deliverable achievement', 'verbose_name_plural': '06. Monthly deliverable achievements'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlyphoto',
            options={'verbose_name': 'Monthly photo', 'verbose_name_plural': '07. Monthly photos'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlyreportdetails',
            options={'verbose_name': 'Monthly report', 'verbose_name_plural': '03. Monthly reports'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectmonthlyworkprogress',
            options={'verbose_name': 'Monthly work progress', 'verbose_name_plural': '04. Monthly work progress'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprojectreportdetails',
            options={'verbose_name': 'Sponsor project report', 'verbose_name_plural': '01. Sponsor project reports'},
        ),
        migrations.AlterModelOptions(
            name='workprogressparameter',
            options={'verbose_name': 'Work progress parameter', 'verbose_name_plural': '09. Work progress parameters'},
        ),
        migrations.RemoveIndex(
            model_name='sponsorprojectmonthlyworkprogress',
            name='reports_spo_monthly_8ed8ef_idx',
        ),
        migrations.AddField(
            model_name='sponsorprojectmonthlyreportdetails',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorprojectmonthlyworkprogress',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_work_progress', to='master.Slum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiaryindicator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectdeliverable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectmonthlybeneficiaryvalue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectmonthlydeliverableachievement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectmonthlyphoto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectmonthlyreportdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectmonthlyworkprogress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorprojectreportdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workprogressparameter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorprojectmonthlyworkprogress',
            unique_together={('monthly_report', 'location', 'parameter')},
        ),
        migrations.AddIndex(
            model_name='sponsorprojectmonthlyworkprogress',
            index=models.Index(fields=['monthly_report', 'location'], name='reports_spo_monthly_477bd3_idx'),
        ),
    ]
