# Generated by Django 3.0.7 on 2021-08-19 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0016_auto_20200219_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.IntegerField(null=True, verbose_name='House Number')),
                ('city', models.IntegerField(null=True)),
                ('covid_uuid', models.CharField(max_length=100, null=True, verbose_name='Covid UUID')),
                ('surveyor_name', models.CharField(max_length=100, null=True, verbose_name='Name of the surveyor')),
                ('date_of_survey', models.DateField(null=True, verbose_name='Date Of Survey')),
                ('last_modified_date', models.DateField(null=True, verbose_name='Last Modified Date')),
                ('family_member_name', models.CharField(max_length=100, null=True, verbose_name='Family member name')),
                ('gender', models.CharField(max_length=100, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('aadhar_number', models.CharField(max_length=100, null=True, verbose_name='Addhar number')),
                ('do_you_have_any_other_disease', models.CharField(max_length=100, null=True, verbose_name='Do you have any other disease')),
                ('if_any_then_which_disease', models.CharField(max_length=100, null=True, verbose_name='If any then which disease')),
                ('preganant_or_lactating_mother', models.CharField(max_length=100, null=True, verbose_name='are you pregnant or lactating mother?')),
                ('registered_for_covid_vaccination', models.CharField(max_length=100, null=True, verbose_name='Have you registered for covid vaccination?')),
                ('registered_phone_number', models.CharField(max_length=100, null=True, verbose_name='Registered Phone Number')),
                ('take_first_dose', models.CharField(max_length=100, null=True, verbose_name='Did you take first dose?')),
                ('first_dose_date', models.DateField(null=True, verbose_name='Date of first dose?')),
                ('vaccine_name', models.CharField(max_length=100, null=True, verbose_name='Which vaccine taken?')),
                ('take_second_dose', models.CharField(max_length=100, null=True, verbose_name='Did you take second dose?')),
                ('second_dose_date', models.DateField(null=True, verbose_name='Date of second dose?')),
                ('corona_infected', models.CharField(max_length=100, null=True, verbose_name='Have you even been infected with corona?')),
                ('if_corona_infected_days', models.CharField(max_length=100, null=True, verbose_name='If corona infected, how many days it had been since infection?')),
                ('willing_to_vaccinated', models.CharField(max_length=100, null=True, verbose_name='Are you willing to get vaccinated?')),
                ('if_not_why', models.TextField(null=True, verbose_name='If not, why?')),
                ('note', models.TextField(null=True, verbose_name='Note')),
                ('slum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Slum')),
            ],
        ),
    ]
