# Generated by Django 3.0.7 on 2024-01-30 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0017_auto_20210819_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='kutcha_household_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='puccha_household_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='semi_puccha_household_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
