# Generated by Django 3.0.7 on 2024-03-04 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0018_auto_20240130_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='other_services_toilet_coverage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='shared_group_toilet_coverage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='toilet_data_available',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='waste_data_available',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='water_data_available',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
