# Generated by Django 3.0.7 on 2025-02-18 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0019_auto_20240304_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.IntegerField(null=True, verbose_name='House Number')),
                ('member_uuid', models.CharField(blank=True, max_length=100, verbose_name='Member Uuid')),
                ('member_first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('member_last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=2, verbose_name='Gender')),
                ('created_date', models.DateField(null=True, verbose_name='Created date')),
                ('submission_date', models.DateField(null=True, verbose_name='Last Modified date')),
                ('member_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('slum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Slum')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProgramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_uuid', models.CharField(blank=True, max_length=100, verbose_name='Program uuid')),
                ('program_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('created_date', models.DateField(null=True, verbose_name='Program Enrolment date')),
                ('submission_date', models.DateField(null=True, verbose_name='Last Modified date')),
                ('program_exit_date', models.DateField(null=True, verbose_name='Program Exit date')),
                ('program_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.MemberData', verbose_name='Member Id')),
                ('slum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Slum', verbose_name='Slum Id')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEncounterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_uuid', models.CharField(blank=True, max_length=100, verbose_name='Encounter uuid')),
                ('encounter_name', models.CharField(blank=True, max_length=100, verbose_name='Encounter uuid')),
                ('created_date', models.DateField(null=True, verbose_name='Created date')),
                ('submission_date', models.DateField(null=True, verbose_name='Last Modified date')),
                ('encounter_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.MemberData', verbose_name='Member Id')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphs.MemberProgramData', verbose_name='Program Enrollment Id')),
                ('slum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Slum', verbose_name='Slum Id')),
            ],
        ),
    ]
