# Generated by Django 3.0.7 on 2025-02-24 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0020_auto_20250218_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_records', models.IntegerField(default=0)),
                ('inserted_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_details', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDataETL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slum_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('household_number', models.IntegerField(blank=True, null=True)),
                ('member_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.CharField(blank=True, max_length=255, null=True)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('children_count', models.CharField(blank=True, max_length=255, null=True)),
                ('menstruation_status', models.CharField(blank=True, max_length=255, null=True)),
                ('mhm_program_enrollment', models.CharField(blank=True, max_length=20, verbose_name='Enrollment In MHM')),
                ('available_followup_cnt', models.IntegerField(blank=True, null=True)),
                ('cup_used_in_last_followup', models.CharField(blank=True, max_length=20, verbose_name='Cup Used In Last Follow-up')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.MemberData', verbose_name='Slum Id')),
                ('slum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Slum', verbose_name='Slum Id')),
            ],
        ),
    ]
