# Generated by Django 3.0.7 on 2025-09-09 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0021_auto_20250224_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householddata',
            name='household_number',
            field=models.CharField(max_length=6),
        ),

    ]
