# Generated by Django 3.0.7 on 2026-04-10 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20260410_1614'),
        ('graphs', '0022_auto_20250909_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_hash', models.CharField(max_length=64, unique=True)),
                ('response', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='followupdata',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='master.City'),
        ),
        migrations.AlterField(
            model_name='followupdata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='followupdata',
            name='household_number',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='followupdata',
            name='slum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='master.Slum'),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slumdata',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slumdata',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
